name: edgedb
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install EdgeDB
        run: |
          sudo mkdir -p /usr/local/share/keyrings
          sudo curl --proto '=https' --tlsv1.2 -sSf -o /usr/local/share/keyrings/edgedb-keyring.gpg https://packages.edgedb.com/keys/edgedb-keyring.gpg
          echo deb [signed-by=/usr/local/share/keyrings/edgedb-keyring.gpg] https://packages.edgedb.com/apt $(grep "VERSION_CODENAME=" /etc/os-release | cut -d= -f2) main | sudo tee /etc/apt/sources.list.d/edgedb.list
          sudo apt-get update && sudo apt-get install edgedb-2
      - name: checkout
        uses: actions/checkout@v3
      - name: cache
        uses: Swatinem/rust-cache@v2
      - name: check format and lint
        working-directory: ./edgedb-vs-surrealdb/edgedb
        run: cargo fmt -- --check && cargo clippy --tests -- -Dwarnings
      - name: run tests
        working-directory: ./edgedb-vs-surrealdb/edgedb
        run: cargo test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
